layout_spectrum: 0.9937262
typography_spectrum: 0.679478
color:
  saturation: 0.7478715
  lightness: 0.9650614
  brandStrength: 0.5527435
  rhythmicContrast: 0.03383983
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: breinology
